import { notFound } from "next/navigation";
import Link from "next/link";
import { PageShell } from "../../../components/page-shell";

const studies = {
  bliq:{name:"BliQ Messaging",type:"Enterprise communications platform",overview:"A production communications product supporting messaging and operational workflows across SMS, WhatsApp, VoIP and real-time conversations.",role:"Contributed across backend and full-stack areas including messaging workflows, authentication, billing, broadcasts, Google Contacts synchronization, WebSocket events and VoIP configuration.",challenge:"High-volume communication workflows require reliable asynchronous processing while keeping application behavior understandable and operationally manageable.",solution:"Worked with queue-based processing, batching, Redis and database-query improvements alongside Spring Boot services and real-time messaging infrastructure.",stack:"Java · Spring Boot · React · MySQL · MongoDB · Redis · RabbitMQ · WebSockets · Docker"},
  techflu:{name:"Techflu",type:"B2B & B2C technology rental platform",overview:"A production rental platform supporting individual customers and enterprise bulk-rental operations.",role:"Developed product workflows covering inventory reservations, bookings, recurring payments, KYC, order management, delivery operations, discounts and promo codes.",challenge:"Rental systems must coordinate inventory availability, payment state and operational workflows without creating inconsistent reservations or orders.",solution:"Built backend workflows using PostgreSQL, Redis, BullMQ and scheduled jobs, with integrations including Razorpay AutoPay, Amazon S3 and Digio.",stack:"NestJS · Next.js · PostgreSQL · Redis · BullMQ · Docker · Razorpay · Amazon S3 · Digio"},
  idp:{name:"Multi-tenant IDP",type:"Reusable identity platform",overview:"A reusable authentication and authorization foundation designed for multiple SaaS applications and tenants.",role:"Designed the system around centralized authentication, tenant isolation, user management and role-based authorization.",challenge:"A reusable identity layer needs to keep tenant boundaries clear while supporting multiple login mechanisms and authorization models.",solution:"Designed JWT authentication, OTP login, Google OAuth, RBAC and tenant-aware APIs using Spring Boot and PostgreSQL.",stack:"Java · Spring Boot · PostgreSQL · React · JWT · OTP · Google OAuth · RBAC"}
} as const;

type Slug=keyof typeof studies;
export function generateStaticParams(){return Object.keys(studies).map(slug=>({slug}));}
export default async function CaseStudy({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const item=studies[slug as Slug];if(!item)notFound();return <PageShell><section className="hero shell innerHero"><div className="eyebrow"><i/>CASE STUDY · {item.type}</div><h1>{item.name}</h1><p className="lead">{item.overview}</p></section><section className="section shell caseStudy"><div><span className="kicker">MY ROLE</span><h2>Contribution</h2><p>{item.role}</p></div><div><span className="kicker">ENGINEERING CHALLENGE</span><h2>The problem</h2><p>{item.challenge}</p></div><div><span className="kicker">APPROACH</span><h2>How it was addressed</h2><p>{item.solution}</p></div><div><span className="kicker">TECHNOLOGY</span><h2>Stack</h2><p>{item.stack}</p></div><div className="contactCard"><h2>Working on something similar?</h2><p>I can help with backend systems, product features, integrations and existing application improvements.</p><Link className="button" href="/contact">Discuss your project ↗</Link></div></section></PageShell>}
